/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package test.sysprop

import spock.lang.Specification

class LibraryTest extends Specification {
    def "someLibraryMethod returns true"() {
        setup:
        def lib = new Library()

        when:
        def result = lib.someLibraryMethod()

        then:
        result == true
    }

    def "sysprop value is set"() {
        when:
        def sysPropVal = System.properties['test_sysprop']
        println "test_sysprop = $sysPropVal"

        then:
        sysPropVal.endsWith('working-dir')
    }
}
